export const subscribitions = [
  {
    name: "Пробные занятия",
    types: [
      {
        key: "T1",
        name: 1,
        duration: "Групповое занятие",
        advantages: [],
        price: "400 ₽",
        oldPrice: "900 ₽",
        sale: "-55%",
      },
      {
        key: "T2",
        name: 1,
        duration: "Индивидуальное занятие",
        advantages: [],
        price: "700 ₽",
        oldPrice: "1.800 ₽",
        sale: "-55%",
      },
      {
        key: "T3",
        name: 1,
        duration: "Сплит-тренировка",
        advantages: [],
        price: "550 ₽ с человека",
        oldPrice: "1.500 ₽",
        sale: "-65%",
      },
    ],
  },
  {
    name: "Групповые абонементы",
    types: [
      {
        key: "G1",
        name: 24,
        duration: "3 месяца",
        advantages: ["1 неделя заморозки"],
        price: "11.000 ₽",
        oldPrice: "12.223 ₽",
        sale: "-10%",
      },
      {
        key: "G2",
        name: 48,
        duration: "6 месяцев",
        advantages: [
          "2 недели заморозки",
          "1 индивидуальная тренировка",
          "футболка с логотипом студии",
        ],
        price: "21.000 ₽",
        oldPrice: "24.706 ₽",
        sale: "-15%",
      },
      {
        key: "G3",
        name: 96,
        duration: "12 месяцев",
        advantages: [
          "4 недели заморозки",
          "2 индивидуальные тренировки",
          "футболка с логотипом студии",
        ],
        price: "40.000 ₽",
        oldPrice: "50.000 ₽",
        sale: "-20%",
      },
    ],
  },
  {
    name: "Индивидуальные абонементы",
    types: [
      {
        key: "I1",
        name: 8,
        duration: "2 месяца",
        advantages: ["1 неделя заморозки"],
        price: "8.680 ₽",
        oldPrice: "12.400 ₽",
        sale: "-30%",
      },
      {
        key: "I2",
        name: 12,
        duration: "3 месяца",
        advantages: ["2 недели заморозки"],
        price: "12.600 ₽",
        oldPrice: "18.000 ₽",
        sale: "-30%",
      },
      {
        key: "I3",
        name: 24,
        duration: "4 месяцев",
        advantages: ["3 недели заморозки", "футболка с логотипом студии"],
        price: "24.360 ₽",
        oldPrice: "34.800 ₽",
        sale: "-30%",
      },
    ],
  },
  {
    name: "Сплит абонементы",
    types: [
      {
        key: "S1",
        name: 8,
        duration: "2 месяца",
        advantages: ["1 неделя заморозки"],
        price: "7.000 ₽ с человека",
        oldPrice: "10.000 ₽",
        sale: "-30%",
      },
      {
        key: "S2",
        name: 12,
        duration: "3 месяца",
        advantages: ["2 недели заморозки"],
        price: "10.080 ₽ с человека",
        oldPrice: "14.400 ₽",
        sale: "-30%",
      },
      {
        key: "S3",
        name: 24,
        duration: "4 месяца",
        advantages: ["3 недели заморозки", "футболки с логотипом студии"],
        price: "18.480 ₽ с человека",
        oldPrice: "26.400 ₽",
        sale: "-30%",
      },
    ],
  },
];
